# -*- coding: utf-8 -*-
"""ImportImageDataGeneratorLibrary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YtHBhJ02L64-UWI_blzbRHrzlbbPRb4e
"""

#importing image data generator library

from keras.preprocessing.image import ImageDataGenerator